import Foundation
import AppKit

/// One pasteboard item's full set of typed representations.
struct PBItemSnapshot {
    var representations: [String: Data]

    func data(forAnyOf utis: [String]) -> (uti: String, data: Data)? {
        for uti in utis {
            if let data = representations[uti] { return (uti, data) }
        }
        return nil
    }
}

/// A complete capture of the pasteboard at one instant.
///
/// A single copy usually publishes several representations at once -- copying a
/// cell range out of Excel yields RTF, HTML, plain text *and* a TIFF. Keeping
/// all of them is what lets a later paste land in the destination app with the
/// same fidelity as the original copy.
struct PasteboardSnapshot {
    var items: [PBItemSnapshot]
    var sourceBundleID: String?
    var sourceAppName: String?
    var capturedAt: Date

    var isEmpty: Bool {
        items.allSatisfy { $0.representations.isEmpty }
    }

    var totalByteSize: Int {
        items.reduce(0) { partial, item in
            partial + item.representations.values.reduce(0) { $0 + $1.count }
        }
    }

    /// Every UTI present anywhere in the snapshot.
    var allUTIs: Set<String> {
        var result: Set<String> = []
        for item in items { result.formUnion(item.representations.keys) }
        return result
    }

    /// Plain text from the first item that carries any, trimmed.
    var plainText: String? {
        for item in items {
            if let data = item.data(forAnyOf: UTIs.plainTextFamily)?.data,
               let string = String(data: data, encoding: .utf8) ?? String(data: data, encoding: .utf16) {
                let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
                if !trimmed.isEmpty { return trimmed }
            }
        }
        return nil
    }

    /// File URLs across all items, in pasteboard order.
    var fileURLs: [URL] {
        var urls: [URL] = []
        for item in items {
            guard let data = item.representations[UTIs.fileURL],
                  let string = String(data: data, encoding: .utf8),
                  let url = URL(string: string)
            else { continue }
            urls.append(url)
        }
        return urls
    }

    /// The best image representation available, preferring already-compressed
    /// formats over TIFF.
    func bestImage() -> (uti: String, data: Data)? {
        for item in items {
            if let found = item.data(forAnyOf: UTIs.imagePreferenceOrder) { return found }
        }
        return nil
    }
}

enum UTIs {
    static let plainText   = "public.utf8-plain-text"
    static let utf16Text   = "public.utf16-external-plain-text"
    static let legacyText  = "NSStringPboardType"
    static let rtf         = "public.rtf"
    static let rtfd        = "com.apple.flat-rtfd"
    static let html        = "public.html"
    static let fileURL     = "public.file-url"
    static let url         = "public.url"
    static let png         = "public.png"
    static let tiff        = "public.tiff"
    static let jpeg        = "public.jpeg"
    static let gif         = "com.compuserve.gif"
    static let heic        = "public.heic"
    static let pdf         = "com.adobe.pdf"

    /// Set by password managers (1Password, Bitwarden and friends) via the
    /// nspasteboard.org convention to mark a copy as secret. Honouring it is
    /// the single most important privacy behaviour a clipboard manager has.
    static let concealed     = "org.nspasteboard.ConcealedType"
    static let transient     = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    static let plainTextFamily = [plainText, utf16Text, legacyText]

    /// Compressed formats first: if an app offers both PNG and TIFF we would
    /// much rather keep the PNG.
    static let imagePreferenceOrder = [png, heic, jpeg, gif, tiff, pdf]

    static let richTextFamily = [rtf, rtfd, html]
}
